services:
  ursaminor:
    container_name: ursaminor
    ports:
      - 61000:80
    volumes:
      - ~/Desktop/docker/universe/ursaminor/dist/:/usr/share/nginx/html/
      - ~/Desktop/docker/universe/ursaminor/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
